--drop table clinical_trials;
CREATE TABLE clinical_trials(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_nct_id VARCHAR UNIQUE,
  trial_title VARCHAR,
  trial_phase VARCHAR,
  therapeutic_area VARCHAR,
  trial_status VARCHAR,
  start_date DATE,
  estimated_completion_date DATE,
  target_enrollment INT,
  created_at timestamp default CURRENT_TIMESTAMP,
  updated_at timestamp
);


