--drop table study_protocols;
CREATE TABLE study_protocols (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id integer not null,
  version_number varchar UNIQUE,
  protocol_document json,
  approval_date date,
  approved_by_user_id integer not null,
  electronic_signature varchar,
  amendment_number integer,
  valid_from date,
  valid_to date,
  created_at timestamp default CURRENT_TIMESTAMP
);

----alter statements 
ALTER TABLE study_protocols ADD FOREIGN KEY (trial_id) REFERENCES clinical_trials(id);

ALTER TABLE study_protocols ADD FOREIGN KEY (approved_by_user_id) REFERENCES users (id);