--drop table study_sites;
CREATE TABLE study_sites (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id integer not null,
  institution_name varchar,
  country varchar,
  site_status varchar,
  target_enrollment integer,
  current_enrollment integer,
  site_initiation_date date,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp
);

--
ALTER TABLE study_sites ADD FOREIGN KEY (trial_id) REFERENCES clinical_trials (id);