--drop table eligibility_criteria;
CREATE TABLE eligibility_criteria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id integer not null,
  criterion_type varchar,
  criterion_text text,
  is_mandatory boolean,
  criterion_logic varchar,
  created_at timestamp default CURRENT_TIMESTAMP
);

-- 
ALTER TABLE eligibility_criteria ADD FOREIGN KEY (trial_id) REFERENCES clinical_trials(id);