--drop table patients
CREATE TABLE patients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_patient_id varchar UNIQUE,
  site_id integer not null,
  screening_number varchar,
  patient_status varchar,
  date_of_birth date,
  gender varchar,
  enrollment_date date,
  created_at timestamp default CURRENT_TIMESTAMP,
  updated_at timestamp
);

ALTER TABLE patients ADD COLUMN full_name VARCHAR;

--alters
ALTER TABLE patients ADD FOREIGN KEY (site_id) REFERENCES study_sites (id);