--drop table patient_screening;
CREATE TABLE patient_screening (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id integer not null,
  screening_date date,
  screening_status varchar,
  eligibility_score integer,
  manual_override boolean,
  override_reason text
);
--alter 
ALTER TABLE patient_screening ADD FOREIGN KEY (patient_id) REFERENCES patients (id);