CREATE TABLE screening_failures (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  screening_id integer not null,
  criterion_id integer not null,
  failure_reason text
);

--
ALTER TABLE screening_failures ADD FOREIGN KEY (screening_id) REFERENCES patient_screening (id);

ALTER TABLE screening_failures ADD FOREIGN KEY (criterion_id) REFERENCES eligibility_criteria (id);