CREATE TABLE informed_consent (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id integer UNIQUE,
  consent_date date,
  digital_signature varchar,
  is_withdrawn boolean,
  withdrawal_date date,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

--
ALTER TABLE informed_consent ADD FOREIGN KEY (patient_id) REFERENCES patients(id);