CREATE TABLE treatment_arms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id integer not null,
  arm_code varchar UNIQUE,
  arm_description text,
  treatment_description text,
  allocation_ratio decimal,
  blinding_level varchar
);
--
ALTER TABLE treatment_arms ADD FOREIGN KEY (trial_id) REFERENCES clinical_trials (id);