CREATE TABLE randomization_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id integer UNIQUE not null,
  arm_id integer not null,
  randomization_date date,
  randomization_method varchar,
  stratification_profile json,
  unblinding_date date,
  random_seed integer,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

--
ALTER TABLE randomization_assignments ADD FOREIGN KEY (patient_id) REFERENCES patients (id);

ALTER TABLE "randomization_assignments" ADD FOREIGN KEY (arm_id) REFERENCES treatment_arms(id);