CREATE TABLE stratification_factors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id integer,
  factor_name varchar,
  factor_levels json,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

--
ALTER TABLE stratification_factors ADD FOREIGN KEY (trial_id) REFERENCES clinical_trials (id);