CREATE TABLE visit_schedules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id integer,
  visit_number integer,
  visit_name varchar,
  visit_window_before_days integer,
  visit_window_after_days integer,
  day_offset integer,
  required_procedures json,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

--
ALTER TABLE visit_schedules ADD FOREIGN KEY (trial_id) REFERENCES clinical_trials (id);