CREATE TABLE patient_visits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id integer not null,
  visit_schedules_id integer,
  scheduled_date date,
  actual_visit_date date,
  visit_status varchar,
  visit_window_status varchar,
  data_queries_count integer,
  days_delayed integer,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

--
ALTER TABLE patient_visits ADD FOREIGN KEY (patient_id) REFERENCES patients (id);

ALTER TABLE patient_visits ADD FOREIGN KEY (visit_schedules_id) REFERENCES visit_schedules (id);