CREATE TABLE ecrf_definitions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id integer,
  ecrf_name varchar,
  ecrf_schema json,
  validation_rules json,
  signature_required boolean,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ecrf_definitions ADD FOREIGN KEY (trial_id) REFERENCES clinical_trials (id);