drop table ecrf_data;
CREATE TABLE ecrf_data (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ecrf_def_id integer not null,
  patient_id integer,
  visit_instance_id integer,
  entered_by_user_id integer,
  form_status varchar,
  form_data json,
  data_entry_date timestamp,
  investigator_signature varchar,
  query_count integer,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp
);

--
ALTER TABLE ecrf_data ADD FOREIGN KEY (ecrf_def_id) REFERENCES ecrf_definitions (id);

ALTER TABLE ecrf_data ADD FOREIGN KEY (patient_id) REFERENCES patients (id);

ALTER TABLE ecrf_data ADD FOREIGN KEY (visit_instance_id) REFERENCES patient_visits (id);

ALTER TABLE ecrf_data ADD FOREIGN KEY (entered_by_user_id) REFERENCES users (id);

