CREATE TABLE laboratory_tests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_name varchar,
  test_code_loinc varchar UNIQUE,
  unit_of_measure varchar,
  reference_ranges json,
  critical_low_value decimal,
  critical_high_value decimal,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);