CREATE TABLE vital_signs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id integer,
  visit_instance_id integer,
  measurement_time timestamp,
  systolic_bp integer,
  diastolic_bp integer,
  heart_rate integer,
  temperature decimal,
  oxygen_saturation decimal,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

--
ALTER TABLE vital_signs ADD FOREIGN KEY (patient_id) REFERENCES patients (id);

ALTER TABLE vital_signs ADD FOREIGN KEY (visit_instance_id) REFERENCES patient_visits (id);