CREATE TABLE medical_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id integer,
  visit_instance_id integer,
  image_type varchar,
  image_date date,
  imaging_protocol varchar,
  file_path varchar,
  radiologist_review text
);

--
ALTER TABLE medical_images ADD FOREIGN KEY (patient_id) REFERENCES patients(id);

ALTER TABLE medical_images ADD FOREIGN KEY (visit_instance_id) REFERENCES patient_visits(id);