CREATE TABLE adverse_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id integer,
  visit_instance_id integer,
  ae_term varchar,
  ae_start_date date,
  ae_end_date date,
  severity_grade varchar,
  causality_relationship varchar,
  treatment_related boolean,
  results_in_death boolean,
  life_threatening boolean,
  requires_hospitalization boolean,
  ae_description text
);

ALTER TABLE adverse_events ADD FOREIGN KEY (patient_id) REFERENCES patients (id);

ALTER TABLE adverse_events ADD FOREIGN KEY (visit_instance_id) REFERENCES patient_visits (id);
