CREATE TABLE serious_adverse_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ae_id integer UNIQUE,
  sae_report_number varchar UNIQUE,
  regulatory_body varchar,
  report_deadline_date date,
  report_submitted_date date,
  dsmb_review_date date,
  sae_status varchar,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE serious_adverse_events ADD FOREIGN KEY (ae_id) REFERENCES adverse_events(id);
