CREATE TABLE protocol_deviations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id integer,
  visit_instance_id integer,
  deviation_type varchar,
  deviation_date date,
  description text,
  corrective_action text,
  reported_to_irb boolean,
  reported_by_user_id integer
);

--
ALTER TABLE protocol_deviations ADD FOREIGN KEY (patient_id) REFERENCES patients (id);

ALTER TABLE protocol_deviations ADD FOREIGN KEY (visit_instance_id) REFERENCES patient_visits (id);

ALTER TABLE protocol_deviations ADD FOREIGN KEY (reported_by_user_id) REFERENCES users (id);