CREATE TABLE safety_alerts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id integer,
  source_type varchar,
  source_table varchar,
  source_record_id integer,
  visit_instance_id integer,
  alert_code varchar,
  alert_message text,
  alert_severity varchar,
  alert_status varchar,
  acknowledged_by_user_id integer,
  created_at timestamp,
  escalated_at timestamp,
  escalation_level integer,
  measured_value decimal,
  reference_range_low decimal,
  reference_range_high decimal,
  threshold_exceeded_percent decimal
);

ALTER TABLE safety_alerts ADD FOREIGN KEY (patient_id) REFERENCES patients (id);

ALTER TABLE safety_alerts ADD FOREIGN KEY (visit_instance_id) REFERENCES patient_visits (id);

ALTER TABLE safety_alerts ADD FOREIGN KEY (acknowledged_by_user_id) REFERENCES users(id);

