CREATE TABLE dsmb_meetings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id integer,
  meeting_date date,
  meeting_type varchar,
  data_cutoff_date date,
  recommendation text,
  meeting_minutes text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE dsmb_meetings ADD FOREIGN KEY (trial_id) REFERENCES clinical_trials (id);