CREATE TABLE survival_analysis (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id integer,
  endpoint_type varchar,
  time_points json,
  survival_probabilities json,
  hazard_ratio decimal,
  logrank_p_value decimal,
  confidence_interval_95 json,
  calculated_at timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE survival_analysis ADD FOREIGN KEY (trial_id) REFERENCES clinical_trials (id);