CREATE TABLE data_locks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id integer,
  lock_type varchar,
  lock_date date,
  locked_by_user_id integer,
  unlock_date date,
  snapshot_hash varchar,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

--
ALTER TABLE data_locks ADD FOREIGN KEY (trial_id) REFERENCES clinical_trials (id);

ALTER TABLE data_locks ADD FOREIGN KEY (locked_by_user_id) REFERENCES users (id);