CREATE TABLE audit_trail_21cfr(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name varchar,
  record_id integer,
  column_name varchar,
  action_type varchar,
  old_value text,
  new_value text,
  changed_by_user_id integer,
  change_timestamp timestamp,
  change_reason text,
  ip_address varchar,
  data_hash varchar
);

ALTER TABLE audit_trail_21cfr ADD FOREIGN KEY (changed_by_user_id) REFERENCES users(id);