CREATE TABLE electronic_signatures (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signatory_user_id integer,
  document_type varchar,
  document_id integer,
  signature_hash varchar,
  signing_reason varchar,
  signed_at timestamp
);

ALTER TABLE electronic_signatures ADD FOREIGN KEY (signatory_user_id) REFERENCES users (id);

