drop table data_queries;

CREATE TABLE data_queries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ecrf_instance_id integer,
  field_name varchar,
  query_text text,
  query_status varchar,
  raised_by_user_id integer,
  raised_date timestamp,
  response_text text,
  acknowledged_by_user_id integer,
  resolved_by_user_id integer,
  resolved_date timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp
);

ALTER TABLE data_queries ADD FOREIGN KEY (ecrf_instance_id) REFERENCES ecrf_data (id);

ALTER TABLE data_queries ADD FOREIGN KEY (raised_by_user_id) REFERENCES users (id);

ALTER TABLE data_queries ADD FOREIGN KEY (resolved_by_user_id) REFERENCES users (id);
ALTER TABLE data_queries ADD FOREIGN KEY (acknowledged_by_user_id) REFERENCES users(id);
