CREATE TABLE user_access_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer,
  accessed_table varchar,
  accessed_record_id integer,
  access_type varchar,
  access_timestamp timestamp,
  ip_address varchar,
  user_agent varchar,
  session_id varchar
);


ALTER TABLE user_access_log ADD FOREIGN KEY (user_id) REFERENCES users (id);