-- drop table users;
CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar UNIQUE,
  password varchar,
  email varchar UNIQUE,
  role varchar,
  site_id integer,
  is_active boolean,
  last_login timestamp,
  created_at timestamp
);

--
ALTER TABLE users ADD COLUMN full_name VARCHAR;

ALTER TABLE users ADD FOREIGN KEY (site_id) REFERENCES study_sites (id);