CREATE TABLE investigators (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer UNIQUE,
  site_id integer,
  investigator_name varchar,
  medical_license_number varchar UNIQUE,
  gcp_certification_date date,
  electronic_signature_key varchar,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

--
ALTER TABLE investigators ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE investigators ADD FOREIGN KEY (site_id) REFERENCES study_sites (id);